In [18]:
import torch

## 2.1.1 Functions of Pytorch

torch.arange() : create tensor

In [2]:
x = torch.arange(12, dtype = torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

numel() can show the number of elements in the tensor

In [5]:
x.numel()

12

shape can show the dimension and shape of the tensor

In [6]:
x.shape

torch.Size([12])

In [4]:
X = x.reshape(3,4)
X.shape
X

torch.Size([3, 4])

In [7]:
X.numel()

12

torch.zeros((a, b, c))

torch.ones((a, b, c))

Create array with dimension a, b, c full of 0s or 1s.

In [10]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

Other ways to create a tensor

In [12]:
torch.randn(4, 4)

tensor([[-0.6718, -0.8381, -0.5916,  0.0292],
        [ 0.3883,  1.0609,  0.1762,  0.5589],
        [-0.3459, -0.2449, -0.4524,  0.1860],
        [-0.3665,  0.3781, -0.0899, -1.3231]])

In [16]:
y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [17]:
y.shape

torch.Size([3, 4])

## 2.1.2. Indexing and Slicing

Similar to python list, indexing help us to access tensor elements. -1 selects the last row and normally it's [start, end). [1:3] actually only includes rows with index 1 and 2

In [19]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [20]:
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

Slicing allows us to access multiple elements in one line. "a:b" means from a to b - 1

In [21]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 2.1.3. Operations

These operations can calculate each element in tensor

In [23]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

e^x

In [24]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

We can concatenate 2 tensors together along a dimension

In [25]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [26]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [28]:
X.sum(), Y.sum()

(tensor(66.), tensor(30.))

## 2.1.4. Broadcasting

In [29]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

Since shapes of A and B do not match up. Broadcasting produce a larger matrix by replicating along columns of A and rows of B

In [36]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 2.1.5. Saving Memory

"=" in python will allocate new memory for the result

In [37]:
before = id(Y)
Y = Y + X
id(Y) == before

False

Using slicing sign [:], it keeps the original memory

In [40]:
Z = torch.zeros_like(Y)
print(Y,Z)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

tensor([[ 2.,  2.,  6.,  6.],
        [ 5.,  7.,  9., 11.],
        [12., 12., 12., 12.]]) tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
id(Z): 4463601440
id(Z): 4463601440


## 2.1.6. Conversion to Other Python Objects

In [41]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [42]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)